# -*- coding: utf-8 -*-
"""공정용 소모품 사용 예측 수준 증대를 통한 낭비비용 절감(R)_Rev.04.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1umZFAmcg2K_8OwsA_NHgMhGIKUORIizu

# **♨ 공정용 소모품 사용 예측 수준 증대를 통한 낭비비용 절감(R)_Rev.04**

>- 목적 : 소모품 사용량을 예측하여 불필요한 소모품 구매를 방지하고자 함
>- 활용 : 소모품 3개월 선행 계획에 활용
>- 근거 : 작년 같은 기간 및 최근 3개월 소모품 사용량

# Define

## Step01 개선 기회 탐색

### ♫ 해결하고자 하는 질문들

문제) 분기별 정보를 추가하세요.

문제) 21년 7월 합성의약의 소모품 사용이력을 보여주세요.

문제) 21년 3~7월 QC 팀 소모품 사용이력을 보여주세요.

문제) 소독액(6가지 품목) 관련 정보만 추출하세요.

문제) 20년 1분기 QC 팀의 소독액(6가지 품목) 사용량을 확인하세요.

문제) 21년 2분기 각 팀별 소독액(6가지 품목) 사용량 합계를 구하고 내림차순으로 정렬하세요.

문제) 21년 2분기 각 팀별 소독액(6가지 품목) 사용량 합계를 한 눈에 비교할 수 있게 그래프로 그리세요.

## Step02 개선 기회 발굴 및 과제 선정

최근 3개년간 6개 팀에서 사용한 소모품 총 83항목이 분석 대상임

- 데이터 취합 기간 3년

19년 | 20년| 21년
--- | ---| --
- |01월|01월
- |02월|02월
- |03월|03월
- |04월|04월
- |05월|05월
- |06월|06월
- |07월|07월
- | 08월|08월
09월 | 09월|
10월 |10월|
11월 |11월|
12월 |12월|

- 대상 라인

    1) 완제\
2) 원제(1part)\
3) 원제(2part)\
4) 합성\
5) QC\
6) 생지/공무

- 분석 대상 소모품
    - 총 89개 품목

## Step03 Project Y 선정

- 데이터 사이즈
    - 1389 obs. of  11 variables

# Measure

## Step04 데이터 수집 및 검증 계획 수립

### ♫ 데이터 불러오기

# saveRDS(object = consume, file = "consume_2108.rds")

# consume <- readRDS(file = consume_2108.rds)

df <- consume

head(df); str(df)

"""## Step05 데이터 Set 구성

### ♫ 열 쌓기
"""

library(dplyr)

library(tidyverse)

colnames(df)

df_new = df %>%
  gather(key = "Team", value = "Quan", Finished, Substance_1, Substance_2, Complex, QC, Supporting)
df_new %>% head()

str(df); str(df_new)

"""## Step06 데이터 취득 시스템(유용성)검증

### ♫ 데이터 전처리

문제) 데이터의 N/A 를 제거하고, 분기별 정보를 추가하세요.
"""

df_new[is.na(df_new)] <- 0

# df_new = na.omit(df_new)

df_new <- df_new %>% 
  mutate(Quarter = ifelse(Month <= 3, 1,
  ifelse(Month <= 6, 2,
  ifelse(Month <= 9, 3, 4))))

head(df_new); str(df_new)

"""## Step07 프로세스 현수준 파악

## Step08 개선 목표 설정

# Analyze

## Step09 X인자 검증 계획 수립

### ♫ Filter
"""

library(dplyr)

df %>% head()

"""문제) 21년 7월 합성의약의 소모품 사용이력을 보여주세요."""

df_new %>% filter(.,Year == 21 & Month == 7 & Team == 'Complex')

"""## Step10 데이터 취득 및 전처리 실시

문제) 21년 3~7월 QC 팀 소모품 사용이력을 보여주세요.
"""

df_new %>% filter(.,Year == 21 & Month >= 3 & Team == 'QC')

"""## Step11 데이터 탐색

### ♫ 기타 고려할 사항

- 303039 5%Decon-spore(Sporicide)Gallon size
    - 1실에서만 매달 2통 사용 (타라인 사용 X)

## Step12 핵심인자 선정

## Step13 분석 모형 검토

# Improve

## Step14 최적 모형 수립

### ♫ 품목군 분류 및 분석

문제) 소독액(6가지 품목) 관련 정보만 추출하세요.
"""

disinfect <- df_new %>%
    filter(Code == '303031' | Code == '303034' | Code == '303038' | Code == '303041' | Code == '303036' | Code == '303060')
disinfect %>% head() ; str(disinfect)

"""문제) 20년 1분기 QC 팀의 소독액(6가지 품목) 사용량을 확인하세요."""

disinfect %>%
  filter(Team == 'QC' & Year == 20 & Quarter == 1)

"""문제) 21년 2분기 각 팀별 소독액(6가지 품목) 사용량 합계를 구하고 내림차순으로 정렬하세요."""

temp <- disinfect %>%
  filter(Year == 21 & Quarter == 2) %>%
  group_by(Team) %>%
  summarise(Q = sum(Quan)) %>%
  arrange(desc(Q))
temp

"""## Step15 모형 검증 및 최적화

### ♫ 그래프

문제) 21년 2분기 각 팀별 소독액(6가지 품목) 사용량 합계를 한 눈에 비교할 수 있게 그래프로 그리세요.
"""

library(ggplot2)

ggplot(data = temp, aes(x = Team,
    y = Q,
    color = Team)) +
    geom_point()

ggplot(temp, aes(x = Team,
    y = Q,
    color = Team))+
    geom_col()

list = ls()
list

# rm(list=ls())

"""## Step16 개선 결과 검증(Pilot Test)

### ♫ 19~20년 동일 3개월 평균 (한 달치)
"""

list = c(df_new %>%
    group_by(Team) %>%
    summarise())
list

# year, month 설정
year = c(19, 20)
month = c(9, 10, 11)

year_mean_Finished = df_new %>% 
    filter(.,Year %in% year & Month %in% month & Team == 'Finished') %>%
    select(-Unit, -Team, -Quarter) %>%
    group_by(Code) %>%
    summarise(mean = as.integer(mean(Quan))) %>%
    as.data.frame()
#     as.matrix()

year_mean_Finished <- year_mean_Finished[!(year_mean_Finished$mean == 0),]

year_mean_Substance_1 = df_new %>% 
    filter(.,Year %in% year & Month %in% month & Team == 'Substance_1') %>%
    select(-Unit, -Team, -Quarter) %>%
    group_by(Code) %>%
    summarise(mean = as.integer(mean(Quan))) %>%
    as.data.frame()

year_mean_Substance_1 <- year_mean_Substance_1[!(year_mean_Substance_1$mean == 0),]

year_mean_Substance_2 = df_new %>% 
    filter(.,Year %in% year & Month %in% month & Team == 'Substance_2') %>%
    select(-Unit, -Team, -Quarter) %>%
    group_by(Code) %>%
    summarise(mean = as.integer(mean(Quan))) %>%
    as.data.frame()

year_mean_Substance_2 <- year_mean_Substance_2[!(year_mean_Substance_2$mean == 0),]

year_mean_Complex = df_new %>% 
    filter(.,Year %in% year & Month %in% month & Team == 'Complex') %>%
    select(-Unit, -Team, -Quarter) %>%
    group_by(Code) %>%
    summarise(mean = as.integer(mean(Quan))) %>%
    as.data.frame()

year_mean_Complex <- year_mean_Complex[!(year_mean_Complex$mean == 0),]

year_mean_QC = df_new %>% 
    filter(.,Year %in% year & Month %in% month & Team == 'QC') %>%
    select(-Unit, -Team, -Quarter) %>%
    group_by(Code) %>%
    summarise(mean = as.integer(mean(Quan))) %>%
    as.data.frame()

year_mean_QC <- year_mean_QC[!(year_mean_QC$mean == 0),]

year_mean_Supporting = df_new %>% 
    filter(.,Year %in% year & Month %in% month & Team == 'Supporting') %>%
    select(-Unit, -Team, -Quarter) %>%
    group_by(Code) %>%
    summarise(mean = as.integer(mean(Quan))) %>%
    as.data.frame()

year_mean_Supporting <- year_mean_Supporting[!(year_mean_Supporting$mean == 0),]

year_mean = c(year_mean_Finished,
    year_mean_Substance_1,
    year_mean_Substance_2,
    year_mean_Complex,
    year_mean_QC,
    year_mean_Supporting)

str(year_mean)

# write.csv(last_year, "last_year.csv")

# install.packages("openxlsx")

library(openxlsx)

"""### ♫ 21년 최근 3개월 평균 (한 달치)"""

list = c(df_new %>%
    group_by(Team) %>%
    summarise())
list

# year, month 설정
year = c(21)
month = c(6, 7, 8)

month_mean_Finished = df_new %>% 
    filter(.,Year %in% year & Month %in% month & Team == 'Finished') %>%
    select(-Unit, -Team, -Quarter) %>%
    group_by(Code) %>%
    summarise(mean = as.integer(mean(Quan))) %>%
    as.data.frame()

month_mean_Finished <- month_mean_Finished[!(month_mean_Finished$mean == 0),]

month_mean_Substance_1 = df_new %>% 
    filter(.,Year %in% year & Month %in% month & Team == 'Substance_1') %>%
    select(-Unit, -Team, -Quarter) %>%
    group_by(Code) %>%
    summarise(mean = as.integer(mean(Quan))) %>%
    as.data.frame()

month_mean_Substance_1 <- month_mean_Substance_1[!(month_mean_Substance_1$mean == 0),]

month_mean_Substance_2 = df_new %>% 
    filter(.,Year %in% year & Month %in% month & Team == 'Substance_2') %>%
    select(-Unit, -Team, -Quarter) %>%
    group_by(Code) %>%
    summarise(mean = as.integer(mean(Quan))) %>%
    as.data.frame()

month_mean_Substance_2 <- month_mean_Substance_2[!(month_mean_Substance_2$mean == 0),]

month_mean_Complex = df_new %>% 
    filter(.,Year %in% year & Month %in% month & Team == 'Complex') %>%
    select(-Unit, -Team, -Quarter) %>%
    group_by(Code) %>%
    summarise(mean = as.integer(mean(Quan))) %>%
    as.data.frame()

month_mean_Complex <- month_mean_Complex[!(month_mean_Complex$mean == 0),]

month_mean_QC = df_new %>% 
    filter(.,Year %in% year & Month %in% month & Team == 'QC') %>%
    select(-Unit, -Team, -Quarter) %>%
    group_by(Code) %>%
    summarise(mean = as.integer(mean(Quan))) %>%
    as.data.frame()

month_mean_QC <- month_mean_QC[!(month_mean_QC$mean == 0),]

month_mean_Supporting = df_new %>% 
    filter(.,Year %in% year & Month %in% month & Team == 'Supporting') %>%
    select(-Unit, -Team, -Quarter) %>%
    group_by(Code) %>%
    summarise(mean = as.integer(mean(Quan))) %>%
    as.data.frame()

month_mean_Supporting <- month_mean_Supporting[!(month_mean_Supporting$mean == 0),]

month_mean = c(month_mean_Finished,
    month_mean_Substance_1,
    month_mean_Substance_2,
    month_mean_Complex,
    month_mean_QC,
    month_mean_Supporting)
month_mean

"""### ♫ 21년 최근 3개월 이력 (세 달치)"""

list = c(df_new %>%
    group_by(Team) %>%
    summarise())
list

# year, month 설정
year = c(21)
month = c(6, 7, 8)

latest_Finished = df_new %>% 
    filter(.,Year %in% year & Month %in% month & Team == 'Finished') %>%
    arrange(Month)

latest_Finished <- latest_Finished[!(latest_Finished$Quan == 0),]

latest_Substance_1 = df_new %>% 
    filter(.,Year %in% year & Month %in% month & Team == 'Substance_1') %>%
    arrange(Month)

latest_Substance_1 <- latest_Substance_1[!(latest_Substance_1$Quan == 0),]

latest_Substance_2 = df_new %>% 
    filter(.,Year %in% year & Month %in% month & Team == 'Substance_2') %>%
    arrange(Month)

latest_Substance_2 <- latest_Substance_2[!(latest_Substance_2$Quan == 0),]

latest_Complex = df_new %>% 
    filter(.,Year %in% year & Month %in% month & Team == 'Complex') %>%
    arrange(Month)

latest_Complex <- latest_Complex[!(latest_Complex$Quan == 0),]

latest_QC = df_new %>% 
    filter(.,Year %in% year & Month %in% month & Team == 'QC') %>%
    arrange(Month)

latest_QC <- latest_QC[!(latest_QC$Quan == 0),]

latest_Supporting = df_new %>% 
    filter(.,Year %in% year & Month %in% month & Team == 'Supporting') %>%
    arrange(Month)

latest_Supporting <- latest_Supporting[!(latest_Supporting$Quan == 0),]

latest = c(latest_Finished,
    latest_Substance_1,
    latest_Substance_2,
    latest_Complex,
    latest_QC,
    latest_Supporting)

str(latest)

"""### ♫ 엑셀 출력"""

# year_mean 의미
year_01 = "19~20"
month_01 = "9~11"

print(paste("과거 동일 시기 (",year_01,"년", month_01,"월) 매월 평균 사용량"))

print(paste("   year_mean_Finished =", year_01,"년", month_01, "월 총 6개월 완제생산팀 실사용량을 6으로 나눔(1개월 실사용량)"))
print(paste("year_mean_Substance_1 =", year_01,"년", month_01, "월 총 6개월 원제1 실사용량을 6으로 나눔(1개월 실사용량)"))
print(paste("year_mean_Substance_2 =", year_01,"년", month_01, "월 총 6개월 원제2 실사용량을 6으로 나눔(1개월 실사용량)"))
print(paste("    year_mean_Complex =", year_01,"년", month_01, "월 총 6개월 합성의약 실사용량을 6으로 나눔(1개월 실사용량)"))
print(paste("         year_mean_QC =", year_01,"년", month_01, "월 총 6개월 QC팀 실사용량을 6으로 나눔(1개월 실사용량)"))
print(paste(" year_mean_Supporting =", year_01,"년", month_01, "월 총 6개월 생산지원 실사용량을 6으로 나눔(1개월 실사용량)"))

writeLines("\n")

year_02 = "21"
month_02 = "6~8"

print(paste("최근 3개월 (", year_02,"년", month_02,"월) 매월 평균 사용량"))

print(paste("   month_mean_Finished =", year_02,"년", month_02, "월 총 3개월 완제생산팀 실사용량을 3으로 나눔(1개월 실사용량)"))
print(paste("month_mean_Substance_1 =", year_02,"년", month_02, "월 총 3개월 원제1 실사용량을 3으로 나눔(1개월 실사용량)"))
print(paste("month_mean_Substance_2 =", year_02,"년", month_02, "월 총 3개월 원제2 실사용량을 3으로 나눔(1개월 실사용량)"))
print(paste("    month_mean_Complex =", year_02,"년", month_02, "월 총 3개월 합성의약 실사용량을 3으로 나눔(1개월 실사용량)"))
print(paste("         month_mean_QC =", year_02,"년", month_02, "월 총 3개월 QC팀 실사용량을 3으로 나눔(1개월 실사용량)"))
print(paste(" month_mean_Supporting =", year_02,"년", month_02, "월 총 3개월 생산지원 실사용량을 3으로 나눔(1개월 실사용량)"))

writeLines("\n")

print(paste("최근 3개월 (", year_02,"년", month_02,"월) 실사용량 상세"))

print(paste("   latest_Finished =", year_02,"년", month_02, "월 총 3개월 완제생산팀 실사용량 Detail 데이터)"))
print(paste("latest_Substance_1 =", year_02,"년", month_02, "월 총 3개월 원제1 실사용량 Detail 데이터"))
print(paste("latest_Substance_2 =", year_02,"년", month_02, "월 총 3개월 원제2 실사용량 Detail 데이터"))
print(paste("    latest_Complex =", year_02,"년", month_02, "월 총 3개월 합성의약 실사용량 Detail 데이터"))
print(paste("         latest_QC =", year_02,"년", month_02, "월 총 3개월 QC팀 실사용량 Detail 데이터"))
print(paste(" latest_Supporting =", year_02,"년", month_02, "월 총 3개월 생산지원 실사용량 Detail 데이터"))

consume <- createWorkbook('consume')

addWorksheet(consume, "year_mean_Finished")
addWorksheet(consume, "year_mean_Substance_1")
addWorksheet(consume, "year_mean_Substance_2")
addWorksheet(consume, "year_mean_Complex")
addWorksheet(consume, "year_mean_QC")
addWorksheet(consume, "year_mean_Supporting")

writeDataTable(consume,"year_mean_Finished",year_mean_Finished)
writeDataTable(consume,"year_mean_Substance_1",year_mean_Substance_1)
writeDataTable(consume,"year_mean_Substance_2",year_mean_Substance_2)
writeDataTable(consume,"year_mean_Complex",year_mean_Complex)
writeDataTable(consume,"year_mean_QC",year_mean_QC)
writeDataTable(consume,"year_mean_Supporting",year_mean_Supporting)

addWorksheet(consume, "month_mean_Finished")
addWorksheet(consume, "month_mean_Substance_1")
addWorksheet(consume, "month_mean_Substance_2")
addWorksheet(consume, "month_mean_Complex")
addWorksheet(consume, "month_mean_QC")
addWorksheet(consume, "month_mean_Supporting")

writeDataTable(consume,"month_mean_Finished",month_mean_Finished)
writeDataTable(consume, "month_mean_Substance_1",month_mean_Substance_1)
writeDataTable(consume, "month_mean_Substance_2",month_mean_Substance_2)
writeDataTable(consume, "month_mean_Complex",month_mean_Complex)
writeDataTable(consume, "month_mean_QC",month_mean_QC)
writeDataTable(consume, "month_mean_Supporting",month_mean_Supporting)

addWorksheet(consume, "latest_Finished")
addWorksheet(consume, "latest_Substance_1")
addWorksheet(consume, "latest_Substance_2")
addWorksheet(consume, "latest_Complex")
addWorksheet(consume, "latest_QC")
addWorksheet(consume, "latest_Supporting")

writeDataTable(consume, "latest_Finished", latest_Finished)
writeDataTable(consume, "latest_Substance_1", latest_Substance_1)
writeDataTable(consume, "latest_Substance_2", latest_Substance_2)
writeDataTable(consume, "latest_Complex", latest_Complex)
writeDataTable(consume, "latest_QC", latest_QC)
writeDataTable(consume, "latest_Supporting", latest_Supporting)

saveWorkbook(consume, file="answer.xlsx")

"""# Control

## Step17 최적모형 모니터링

R 필요성에 관한 의문?
- 아래 기능들 엑셀로도 가능함

    - 특정 품목 필터링
    - 간단한 사용량 통계 (사용량 합계, 평균 등)
    - 그래프 작성

오히려 생소한 R 코드보다 엑셀 UI 가 직관적이고 처리가 쉬움

R 이 필요한 이유

- 표준화\
    R 은 한 번 스크립트 만들어 놓으면 사용자와 관계없이 동일한 방법으로 분석함\
    엑셀 기능으로 통계치 구할 수도 있지만 방법이 표준화되지 않음
- 통계분석의 자동화\
    매달 업데이트되는 데이터에 관해 동일한 분석 실시해야 한다면, 단순 반복 분석은 R 이 더 편하고 빠름
- 빅데이터\
    데이터가 매달 쌓이는데 엑셀 파일 용량이 20MB 넘어가면 분석하기 부담스러울 것

## Step18 표준화 및 수평전개

추가 업데이트 예정

- 매월 재고수준 반영
- 품목별 유효기한 반영
- 발주시간 고려
- 공급사 사정으로 인한 수급 이슈 고려

end
"""
